### ISSUE TITLE
Links redirect to homepage in nojs browser instead of linked page

### ISSUE THREAD

**Issue by stevenroose** [Blockstream/esplora#138]
I have JS disabled in my browser and links like these just redirect to https://blockstream.info/testnet/nojs/.
https://blockstream.info/testnet/tx/7990d75a600d6cfb4099e5ba5661377f6ed95a127ae03bb1909a82249130f9c4?input:0&expand

**Comment by shesek** [comment]
It is known that the redirection doesn't retain the path with some script blocking extensions, like uMatrix. It does work with some of the other methods for blocking script execution.

Fixing this has some annoying complications, as it would require dynamically generating the HTML response in the yesjs version and inserting the requested path into it, rather than it being a statically served html file as it is today. @greenaddress and I decided to avoid this complication when this was implemented, but I've been hearing from several people that bumped into this... maybe worth reconsidering?

**Comment by stevenroose** [comment]
My versions:
```
firefox 68.0.2-1
uBlock Origin 1.20.0
```

**Comment by stevenroose** [comment]
@shesek, are you saying that the `/tx/deadbeef` specific pages are all the same HTML and load the content dynamically using JS after the HTML page is loaded? In that case I understand that it's a lot harder to do nojs.

But if a nojs rendering exists in `/html/tx/deadbeef`, would it be hard to generate a hybrid? Like loading the information for the requested path on rendering and just using the JS for search/clicks?

**Comment by greenaddress** [comment]
works with chrome and firefox, please report to provider of the extension(s)
