### ISSUE TITLE
Troubles with running dev-server in Docker container

### ISSUE THREAD

**Issue by altafan** [Blockstream/esplora#156]
I'm trying to run esplora in dev mode into a Docker container with this simple Dockerfile:

```dockerfile
FROM node:latest

RUN git clone https://github.com/Blockstream/esplora.git && \
  cd esplora && \
  npm install && npm run postinstall

WORKDIR /esplora

ENV CORS_ALLOW=*

EXPOSE 5000

CMD [ "npm", "run", "dev-server" ]
```

Since I'm using an existing compose with an electrs service, I run the container attaching to the existing docker network with:

`docker run -d -p 5005:5000 --network resources_local -e API_URL=http://localhost:3001 esplora-test`

Looking at the console, everything is ok in the communication between esplora and electrs, but if I click on any block to see the transactions I get the following error:
`TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.`

<img width="1280" alt="Schermata 2019-11-22 alle 17 59 51" src="https://user-images.githubusercontent.com/18440657/69445116-9a41d200-0d49-11ea-9ddc-ab1932aa1e98.png">

Esplora works without errors, instead, if I run it on my mac.

**Comment by shesek** [comment]
This seems quite odd, is there any way that I could access a live version of this?

**Comment by altafan** [comment]
Unfortunately no :( But you can build your own image and run the container as I'm actually doing. You can use the Dockerfile above.

**Comment by shesek** [comment]
I was able to reproduce this locally. It appears like this was caused due to npm not liking to run installation scripts as root (it [drops permissions to `nobody`](https://docs.npmjs.com/misc/scripts#user), which was preventing the postinstall script from running properly).

Since we're inside docker and running as root is fine, you can fix this by enabling `unsafe-perm` like we do [in esplora's Dockerfile](https://github.com/Blockstream/esplora/blob/6240c46a4b8acf2487ce123be1d374e214c87386/Dockerfile#L24) (you can also use `npm install --unsafe-perm` instead of setting the global config option). With this, you can also remove the explicit `npm run postinstall` call you added.

Here's a complete example that I tested to work locally:

```
FROM node:latest

RUN git clone https://github.com/Blockstream/esplora.git && \
  cd esplora && \
  npm install --unsafe-perm

WORKDIR /esplora

ENV CORS_ALLOW=*

EXPOSE 5000

CMD [ "npm", "run", "dev-server" ]
```

Also note that you only really need `CORS_ALLOW` if there are going to be third-party origins loading static assets from your dev-server. I'm using this for local development of the prerendered/nojs server, which loads the static assets from my local dev-server. Other than this, there isn't much of a reason to use `CORS_ALLOW`. (note that this is different from electrs's `--cors` argument, which you probably should use)

Finally, if this is meant for production and not for development, you'd ideally want to pre-build the esplora web ui as a static directory (set env variables config and `npm run dist`) and have your docker use something like nginx to serve them directly.

**Comment by shesek** [comment]
P.S. I recently wrote [instructions for installing esplora+electrs](https://bitcoin.stackexchange.com/questions/91746/configure-esplora-to-point-to-the-bitcoind-servers-ip-address/91859#91859) that you might find useful.

**Comment by altafan** [comment]
Thank you for your exhaustive answer! I just tested and it works nice.

>Finally, if this is meant for production and not for development, you'd ideally want to pre-build the esplora web ui as a static directory (set env variables config and npm run dist) and use something like nginx to serve them directly.

Exactly, I am already using  a statis dist dir for production served with nginx.

One thing I personally don't like so much is that I have to move at least the `npm run dist` and `nginx` operations into a bash script and use it as the entrypoint of my container in order to be able to pass the `API_URL` environment variable when running the container, otherwise I would be forced to use a build argument when building the docker image, but it's not that big problem after all.

**Comment by shesek** [comment]
Awesome! Glad this worked out.

> One thing I personally don't like so much is that I have to move at least the npm run dist and nginx operations into a bash script and use it as the entrypoint of my container in order to be able to pass the API_URL environment variable when running the container, otherwise I would be forced to use a build argument when building the docker image, but it's not that big problem after all.

Yeah, that's a bit complicated because the API_URL is injected into the source code at build time by replacing literal `process.env.API_URL` references (via [envify](https://github.com/hughsk/envify#readme)).

But if nothing is specified, the AP_URL defaults to `/api`. Perhaps it could be more convenient for you to setup the nginx server serving the static files to also reverse-proxy `/api` to your electrs server?

Another thing you could do is `sed -i 's#"/api"#"https://electrs.server/"#g' dist/app.js`. But that's pretty hacky, dunno if you should really do that :p

**Comment by jodobear** [comment]
> Finally, if this is meant for production and not for development, you'd ideally want to pre-build the esplora web ui as a static directory (set env variables config and npm run dist) and use something like nginx to serve them directly.

I followed your instructions to the dot, but when I do `npm run dist`, i get the following but the site doesn't load:

```+ shopt -s extglob
+ export DEST=dist
+ DEST=dist
+ export NODE_ENV=production
+ NODE_ENV=production
+ export BASE_HREF=/
+ BASE_HREF=/
+ export API_URL=/api
+ API_URL=/api
+ mkdir -p dist
+ rm -rf 'dist/*'
+ [[ -d node_modules ]]
+ cd client
+ [[ -d node_modules ]]
+ cp -RL www/bootstrap.min.css www/font www/img www/instascan.min.js www/light-theme_style.css www/style.css dist/
+ '[' -n '' ']'
+ pug client/index.pug -o dist

  rendered /home/standup/esplora/dist/index.html
+ '[' -n '' ']'
+ cat dist/style.css
+ node -p 'require('\''cssjanus'\'').transform(fs.readFileSync('\''/dev/stdin'\'').toString(), false, true)'
+ cd client
+ browserify --no-dedupe -p bundle-collapser/plugin src/run-browser.js
+ [[ production != \d\e\v\e\l\o\p\m\e\n\t ]]
+ uglifyjs -cm
Browserslist: caniuse-lite is outdated. Please run the following command: `npx browserslist --update-db`
```

while, `npm run dev-server` does load the site. I want to deploy it for production and would like to prebuild the UI.

I'd be grateful if you can point out what's missing or what can I do here. Thanks

**Comment by shesek** [comment]
Did you try running `npx browserslist --update-db`?

**Comment by jodobear** [comment]
Yes, it always results in `No lockfile found. Run "npm install", "yarn install" or "pnpm install"`

I even installed npx using `-g`

**Comment by shesek** [comment]
Ok, I tried building in a fresh environment and was able to reproduce the message you are seeing.

It appears that this is just a warning message - despite it being displayed, everything is still getting built properly to the `dist` directory.

I'll look into making that falsely alarming message go away...

**Comment by jodobear** [comment]
> Ok, I tried building in a fresh environment and was able to reproduce the message you are seeing.
> 
> It appears, however, that this is just a warning message - despite it being displayed, everything is still getting built properly to the `dist` directory.
> 
> I'll look into making that falsely alarming message go away...

It does create `dist` directory and i do see all the relevant files but,

1. Tor browser is `Unable to Connect`
2. `curl: (7) Failed to connect to localhost port 5000: Connection refused`

 while when i run the `dev-server` Tor connects on the same onion address & curl gets the page.

**Comment by shesek** [comment]
`npm run dist` creates the necessary files, but its up to you to serve them. In a production environment you typically wouldn't want a nodejs server to serve static assets, a more full fledged web server like nginx is better suited for this.
