### ISSUE TITLE
Question - Bitcoincore integration and other clients

### ISSUE THREAD

**Issue by adiack** [Blockstream/esplora#17]
Thanks a lot of sharing I got the client up. 

Is there info on connecting it to bitcoin core ( e.g RPC credentials) ? Also would this work with alternative implementation such as btcd, bitcoind ?

**Comment by shesek** [comment]
> Is there info on connecting it to bitcoin core ( e.g RPC credentials) ? 

You can specify `--daemon-dir ~/.bitcoin --daemon-rpc-addr 127.0.0.1:8332 --cookie 'myrpcuser:myrpcpass'`. If you're using bitcoind's cookie file, you don't need to specify the username/password (it'll automatically read the cookie file).

See `--help` or [the original usage docs on romanz/electrs](https://github.com/romanz/electrs/blob/master/doc/usage.md#bitcoind-configuration) for more details.

> Also would this work with alternative implementation such as btcd, bitcoind ?

By default, the initial syncing is done by reading the `blk` files directly from disk. This wouldn't work with alternative implementations like `btcd` that use a different on-disk serialization format.

However, you can specify `--jsonrpc-import` to read blocks using the RPC instead of the `blk` files. This would be *much* slower, but should work with any alternative implementation that has a compatible RPC API.

**Comment by adiack** [comment]
Thank you for the info!

**Comment by greenaddress** [comment]
Closing, feel free to reopen or open a new one if you have more questions.
