### ISSUE TITLE
`reShortTxOut` matches are not appending the output index to the URL

### ISSUE THREAD

**Issue by fiatjaf** [Blockstream/esplora#202]
I see from https://github.com/Blockstream/esplora/blob/7b72fae11c9920d1165a976e21cc2e635d0fea37/client/src/driver/search.js#L39 and https://github.com/Blockstream/esplora/blob/7b72fae11c9920d1165a976e21cc2e635d0fea37/client/src/driver/route.js#L12-L24 that it should be working, but in reality it isn't.

At some point my Cycle.js abilities failed me and I couldn't dig any further, but when I paste a string like `554308x787x0` I'm redirected to `https://blockstream.info/tx/6af2bdeca469d7db5f0a3a7c8c327a6ab580e2b013a0b7244289337a4ec5eb8d`, without `?output:0` appended at the end.

**Comment by shesek** [comment]
Thanks for the report, nice catch!

This appears to be caused by a bug/incompatibility in @cycle/history that [I noticed awhile ago](https://github.com/cyclejs/cyclejs/pull/890#issuecomment-542413707) and tried to [work around in esplora](https://github.com/Blockstream/esplora/blob/1fed3a1b5832695badb8bedb7c757677ae0dc9fe/client/src/app.js#L354-L355), but apparently missed doing this for the `searchResult$` redirection.

I submitted a more complete fix [as a PR to @cycle/history](https://github.com/cyclejs/cyclejs/pull/942) and added a [local patch](https://github.com/Blockstream/esplora/commit/1fed3a1b5832695badb8bedb7c757677ae0dc9fe) in the meanwhile. This should start working with the next deployment.

(P.S. FYI, you can also directly navigate to `https://blockstream.info/<short-channel-id>`. this works with other searches too.)
