### ISSUE TITLE
Sending Address

### ISSUE THREAD

**Issue by wchance** [Blockstream/esplora#266]
When inputting the tx hash we can see the receiving address(es) but we do not see the sending address(es).   How would we go about figuring out which address sent the funds?

**Comment by shesek** [comment]
First of all, note that bitcoin [has no from address](https://en.bitcoin.it/wiki/From_address).

But you can get the address associated with the spent prevout from the tx json via `tx.vin[n].prevout.scriptpubkey_address`.

**Comment by monzturreminem** [comment]
That would mean that I am Bitcoin it makes sense I mean I did make up Satoshi Nakamoto I’m starting to get my swag back I went to my adoptive dads house for dinner and woke up to him telling me to get a job at McDonald’s he was tired of supporting me lol and I’m like hold up didn’t I just give you a check for 1 million he said “I don’t know what your talking about” I’ve been scratching heAd ever since “ but who cRes now I’m back, now if I can just get these banks to use this bitcoin to find an account I’d be great who wants to help me get these banks up to speed and I’m serious call me 2539299952 I’m in SF right now filming and rapping and of course trying to configure and integrate a new centralized banking hub that can fund all the banks in the world they my private non profit government affairs marshall mathers foundation start a repository and make sure I’m on there to contribute (serious business)(I’m also planning an insurance business (I can insure bitcoin)And replace any loss hack or problems that might cause loss of bitcoin I can even retroactivate it to anyone who made mistakes in the very beigining loosing their fortunes but I need a team right now today) I can pay in bitcoin I have zero cash and need help with that too so please pay attention to me and help me out ASAP)(I’ve made decent progress so far but I need this bitcoin in the central banks like yesterday)soon the whole world could blackout with No numbers in their system if I don’t get some help)(step dad killed my accounts and left me dry he thinks he can mirror me and take over what I started on his own)(he is sadly mistaken)(note my whole adopted family does this to me every time I’m working on big projects and then may sister thinks it’s funny to ask me how come nothing ever works out for, “You have a lot of good ideas Yo but how come none of them ever work out for you,” now this bitch got a lock on my royalties so I get a deposit last one in July to my PayPal 20,000 USD just vanished PayPal bot was helpful and said it rerouted to an account that was attracted to my account)(urgency) 

Eminem
