### ISSUE TITLE
address discrepancies

### ISSUE THREAD

**Issue by jlopp** [Blockstream/esplora#376]
Came across this address that seems to be missing transaction data:

https://blockstream.info/address/1AefXTGb6ZfTuEvDqVAGyGHFSxk5zmavuC

Compare to other explorers that should show the original coinbase output and subsequent spend: https://blockchair.com/bitcoin/address/1AefXTGb6ZfTuEvDqVAGyGHFSxk5zmavuC

**Comment by shesek** [comment]
This is because blockchair encodes p2pk scripts as a base58 address as-if it was a p2pkh script. But this is incorrect, p2pk scripts have no address representation.

Some previous discussion here:

- https://github.com/Blockstream/esplora/issues/14
- https://twitter.com/adam3us/status/1265775433389412352
- https://twitter.com/NicolasDorier/status/1087015403581104128
