### ISSUE TITLE
"Transaction not found"

### ISSUE THREAD

**Issue by nopara73** [Blockstream/esplora#40]
https://wasabiwallet.io/  

I recently pointed Wasabi's website to Blockstream.info and it seems like it says "transaction not found" when the coinjoin is unconfirmed. Currently these three are not found:  

c394361f5dbfb01f2a69a2111c36dfb5fe8c8dde0f57a0a5a856a959b2d6ad65
94537ef9853c0641e5220e6f4ffd0b39ba63d847e70175b6c923434a076f2c4c
b293c0e2d4b24bde3ae952fb0f24f9d8af05d9710a61dfb87a82700c2ce6187f

Blockchain.info shows it properly. What can be the issue? Some bitcoind configuration makes you not to show large unconfirmed transactions?

![image](https://user-images.githubusercontent.com/9156103/53187081-9a6a4100-3602-11e9-90d7-aea74a11e6e6.png)

**Comment by greenaddress** [comment]
They are all there now. I think this was due a deployment we did around the same time as the transaction was originally broadcasted and the transaction may have been pushed to us just before we lost mempool and restarted populating it. 

I also noticed some outputs of one of this transaction was at least an input in one of the other (or more). Thanks for the report.

 i don't think is something specifically to do with the explorer or our node configuration since mempool wasn't/isn't full and the fee rate seems ok too. It just happened that the transaction wasn't in the node mempool when you queried for it (and i assume nodes we were connected to would not rebroadcast to us twice) so it's more to do to improve our deployment procedures at this point and work harder to preserve mempool.

**Comment by greenaddress** [comment]
@nopara73 very odd, the moment the explorer had them they also got mined, maybe they weren't too well propagated?

**Comment by greenaddress** [comment]
Another thing you can do next time this happens is to try to broadcast the tx via the explorer, that should also add it if it's valid/not missing any input

**Comment by nopara73** [comment]
I see, thank you, that's plausible. If I notice it again, I'll start propagating coinjoins to the explorer, if it still persist, I reopen the issue.

**Comment by greenaddress** [comment]
@nopara73 thanks!
