### ISSUE TITLE
"asset_entropy" wrong or missing for issuances

### ISSUE THREAD

**Issue by valerio-vaccaro** [Blockstream/esplora#99]
In order to validate an issuance transaction, the liquid-core give you the asset_entropy value that you can use to calculate asset_id and reissuance_token_id. Esplora shows you this information via the API but the value is missing or wrong.

e.g.issuance tx a89e97e9eec81802d65a8f013133267705c2bd249d46ba85f77cdf52778a0ffb

- from https://blockstream.info/liquid/api/tx/a89e97e9eec81802d65a8f013133267705c2bd249d46ba85f77cdf52778a0ffb -> **"asset_entropy":null**
- from liquid-cli getrawtransaction a89e97e9eec81802d65a8f013133267705c2bd249d46ba85f77cdf52778a0ffb 1 -> **"assetEntropy": "cdf01324adba262a22008bd9df697adb5592c0a0c37afddc0f22bc3da2cb76d5"**,

issuance tx d535ded7ce07a0bb9c61d0fefff8127da3fc4833302b05e2b8a0cf9e04446af1

- from https://blockstream.info/liquid/api/tx/d535ded7ce07a0bb9c61d0fefff8127da3fc4833302b05e2b8a0cf9e04446af1 -> **"asset_entropy":"793762dfdbee2d3e6fd0d8f26b922f8575412850ff884df55e1475ec79f1cb56"**
- from liquid-cli getrawtransaction d535ded7ce07a0bb9c61d0fefff8127da3fc4833302b05e2b8a0cf9e04446af1 1 -> **"assetEntropy": "e517d8680fa3d00eb3c5395ee86ed62db1e6f8d31609d3e7f50565dbbcec8023"**

**Comment by shesek** [comment]
The mismatch is due to a somewhat confusing terminology used in rust-elements and cpp-elements that spilled into esplora.

In rust-elements, for initial issuances, the [`asset_entropy`](https://github.com/ElementsProject/rust-elements/blob/ae548a4748508775653a65daa828bb5a0207a325/src/transaction.rs#L34) field of the `AssetIssuance` struct contains the user-provided entropy from the issuance transaction as-is, which is typically referred to as the "contract hash" in cpp-elements. The default entropy, if none was provided by the issuer, is 32 `0x00` bytes. The `null` value signifies that the default value was used (this might be a bit confusing, perhaps I should change that to return the raw zerod-out bytes instead?).

The user-provided entropy is then hashed ([using the fast merkle root algo](https://github.com/ElementsProject/elements/blob/f08447909101bfbbcaf89e382f55c87b2086198a/src/issuance.cpp#L7)) with the outpoint being spent by the issuance input to arrive at the asset entropy. cpp-elements's rpc [converts the `assetEntropy` field](https://github.com/ElementsProject/elements/blob/3689bc83dde273f0be4cb7829db6e346c91d687a/src/wallet/rpcwallet.cpp#L5635-L5646) on issuances from the user-provided entropy to the asset entropy before returning it in rpc replies, while esplora doesn't do that.

For re-issuances, the input contains the derived asset entropy directly, so there's no difference between cpp-elements and rust-elements.

There's an [unmerged PR to rust-elements](https://github.com/ElementsProject/rust-elements/pull/19) which implements the fast merkle root algorithm, as well as the conversion from user-provided entropy and outpoint into the asset entropy, and from the asset entropy to the asset id. I'm already using it on [a development branch](https://github.com/shesek/electrs/commits/201905-asset-index) that extends esplora's support for issued assets. Among other things, it computes the asset entropy/id and adds an `asset_id` field to the issuance json. To be more in-line with cpp-elements's terminology, I'll rename the `asset_entropy` field to `contract_hash` and add a new `asset_entropy` field with the derived asset entropy.

But note that this will probably only be deployed on blockstream.info once the PR to rust-elements is merged. In the meanwhile, if you have a fast merkle root implementation in your environment (or willing to write one), you could compute the asset entropy yourself using the data currently available from the esplora api.

**Comment by shesek** [comment]
Implemented the changes in https://github.com/shesek/electrs/commit/5942c83adb6528658fac7be93f724a8158453f6a.

**Comment by shesek** [comment]
@valerio-vaccaro I'm closing, please report back if you're still having trouble.
